apiVersion: v1
kind: Service
metadata:
  name: test-service-2
  namespace: test
spec:
  type: NodePort
  selector:
    app: my-apps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30012
