apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-rox
  namespace: test
  labels:
    test1: test2   
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath-test ## any storage class

