# 기존 PVC Delete 안되서 Test 하려고 만든거
# 정책 적용하기전 생성하고 정책 적용 후 삭제 진행
# 결과는.. DELETE verb만 있으면 될게 아님..
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-rox-differnet
  namespace: test
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath ## any storage class
