apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multiple-test2-pvc-rwo
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi # not allow 1Ti, 1Mi 1..
  storageClassName: openebs-hostpath-test ## any storage class
