apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multiple-test3-pvc-rwo 
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # not allow 1Ti, 1Mi 1..
  storageClassName: directpv-min-io # test
