apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-rwo
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi # not allow 1Ti, 1Mi 1..
  storageClassName: openebs-hostpath ## any storage class
