apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-rwx
  namespace: test
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1 # not allow 1Ti, 1Mi 1..
  storageClassName: openebs-hostpath ## any storage class
